name: Create Github release

on:
  workflow_dispatch:
  push:
    tags: [v*]

jobs:
  release-notes:
    name: Create Release Notes
    runs-on: self-hosted
    outputs:
      date: ${{ steps.date.outputs.date }}
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Generate Release Notes
        id: gen_release_notes
        run: |
          echo "Release Notes
          " > release_notes.md
          echo "Docker Image
          " >> release_notes.md
          echo "https://hub.docker.com/r/deduard/tools/tags?page=1&name=restart-notifier" >> release_notes.md
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "notes<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cat release_notes.md)." >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.gen_release_notes.outputs.notes }}
          generate_release_notes: true

  build-image:
    name: Build and push Docker image
    needs: [release-notes]
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      docker_tags: deduard/tools:restart-notifier-${{ needs.release-notes.outputs.date }},deduard/tools:restart-notifier-latest
    secrets: inherit